### ISSUE TITLE
Add createWeight() method to the HashQParserPlugin

### ISSUE THREAD

**Issue by joel-bernstein** [Heliosearch/heliosearch#28]
Currently the HashQParserPlugin is implemented only as a PostFilter. This was only meant as a POC of a hash partitioning filter.

This ticket will add the createWeight() method (and any other supporting code), so that the HashQParserPlugin can return a functioning Lucene Query. This will allow the HashQParserPlugin to be cached in the filter cache.

**Comment by joel-bernstein** [comment]
Committed the work for this to the helio_4_10 branch:

https://github.com/Heliosearch/heliosearch/commit/cc767bd270668bf05e59e57699e48bce9f3b2af4

createWeight builds a bitset for each segment in a separate thread. A cached threadpool is used for this. A Semaphore is used to limit the number of active threads working in parallel. 

Not wild about the static synchronized method to add the closeHook. Until there is some kind of shared threadpool mechanism, or QParsePlugins can be made SolrCoreAware, I think we're stuck with this type of approach.

**Comment by yonik** [comment]
You can also implement the DocSetProducer interface:

public interface DocSetProducer {
  public DocSet createDocSet(QueryContext queryContext) throws IOException;
}

That can be more efficient since it allows one to skip all the middle steps and just create a DocSet.
Not sure if that helps in this case or not... just pointing it out for future reference.

**Comment by joel-bernstein** [comment]
I took a quick look at DocSetProducer. Seems to be a new interface in Heliosearch. I'll need to take a deeper look to understand how to make use of it.
